### ISSUE TITLE
build error in ubuntu 14.10

### ISSUE THREAD

**Issue by dzhwinter** [johmathe/Shotdetect#11]
^
/home/dzh/Documents/Shotdetect/src/main.cc:151:10: error: duplicate case value
      '116'
    case 't':
         ^
/home/dzh/Documents/Shotdetect/src/main.cc:134:10: note: previous case defined
      here
    case 't':
         ^
1 warning and 1 error generated.
CMakeFiles/shotdetect-gui.dir/build.make:77: recipe for target 'CMakeFiles/shotdetect-gui.dir/src/main.cc.o' failed
make[2]: *** [CMakeFiles/shotdetect-gui.dir/src/main.cc.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/shotdetect-gui.dir/all' failed
make[1]: *** [CMakeFiles/shotdetect-gui.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

the predependency is satisfiying as you list. only package newer than you is libwgtk3.0-dev.

i'm stuck in this problem about one week. there is no response. LoL

**Comment by dzhwinter** [comment]
Oh

**Comment by jlequeuxbl** [comment]
I hopefully fixed this. Also in the process of adding continuous building and integration with travis.

**Comment by johmathe** [comment]
I (hopefully) fixed this. Also adding travis integration script so that we don't get these surprises anymore.
