### ISSUE TITLE
Make problem 'list' file not found

### ISSUE THREAD

**Issue by BigTundra** [johmathe/Shotdetect#2]
I'm trying to build shotdetect in ubuntu 11.04.  I'm getting the following error:

Virtual-Machine:~/projects/Shotdetect/build$ cmake ..
-- avformat library found: /usr/lib/libavformat.so
-- avdevice library found: /usr/lib/libavdevice.so
-- avcodec library found: /usr/lib/libavcodec.so
-- avutil library found: /usr/lib/libavutil.so
-- swscale library found: /usr/lib/libswscale.so
Found all FFmpeg libraries in /usr/lib/libavformat.so;/usr/lib/libavdevice.so;/usr/lib/libavcodec.so;/usr/lib/libavutil.so;/usr/lib/libswscale.so.
-- Found GD: /usr/lib/libgd.so
Found libgd: /usr/lib/libgd.so;/usr/lib/i386-linux-gnu/libpng.so;/usr/lib/i386-linux-gnu/libz.so;/usr/lib/i386-linux-gnu/libjpeg.so in /usr/include
Found libxml2: /usr/lib/libxml2.so in /usr/include/libxml2
Found libxslt: /usr/lib/libxslt.so in /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shane/projects/Shotdetect/build
Virtual-Machine:~/projects/Shotdetect/build$ make
[ 16%] Building CXX object CMakeFiles/shotdetect.dir/src/film.cc.o
In file included from /home/shane/projects/Shotdetect/src/film.cc:32:
/home/shane/projects/Shotdetect/./src/film.h:17:10: fatal error: 'list' file not found
#include <list>
         ^
1 error generated.
make[2]: *** [CMakeFiles/shotdetect.dir/src/film.cc.o] Error 1
make[1]: *** [CMakeFiles/shotdetect.dir/all] Error 2
make: *** [all] Error 2

Any suggestions?

**Comment by johmathe** [comment]
I'm gonna close this issue, I think this is a little bit out of date :)
